on:  [ push ]

jobs:
  windows_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-2019 ]
    name: bisweb-test
    steps:
    - name: Environment Setup
      run: |
        python --version
        cp /c/hostedtoolcache/windows/Python/3.7.9/x64/python.exe /c/hostedtoolcache/windows/Python/3.7.9/x64/python3.exe
        echo "----------------------------------------------------"
        echo "git = `which git` `git --version`"
        echo "python = `which python` `python --version`"
        echo "python = `which python3` `python3 --version`"
        echo "node = `which node` `node --version`"
        echo "----------------------------------------------------"
        pwd
      shell: bash
